"""Generate ``results/paper_delta.md`` — printed vs computed, side by side.

Three columns for every headline number:

* **paper** — what the PDF prints (Zenodo 10.5281/zenodo.21515696)
* **published cfg** — what the frozen reproduction path computes
* **paper-spec cfg** — what Section 5's described corpus computes

Where a number has no generating code at all, the report says so instead of
quietly filling the cell.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

# --------------------------------------------------------------------------- #
# Everything the paper prints, transcribed from the PDF.
# --------------------------------------------------------------------------- #
PAPER: dict[str, Any] = {
    "stalled_precision": 0.994,
    "stalled_precision_ci": (0.991, 0.997),
    "stalled_recall": 0.983,
    "stalled_recall_ci": (0.977, 0.989),
    "f2": 0.985,
    "pr_auc": 0.861,
    "pr_auc_ci": (0.842, 0.879),
    "brier": 0.0029,
    "brier_ci": (0.0024, 0.0035),
    "reliability": 0.00065,
    "resolution": 0.199,
    "cusum_median": 2,
    "cusum_mean": 2.625,
    "cusum_p95": 5.0,
    "cusum_detection_rate": 1.00,
    "arl": 1465,
    "saved_ips": 2.23e-4,
    "saved_snips": 4.00e-5,
    "saved_dr": 2.78e-4,
    "saved_dr_ci": (2.60e-4, 2.95e-4),
    "mcnemar_liveness_p": 1.9e-196,
    "mcnemar_ratings_p": 5.9e-182,
    "delong_auc": 0.962,
    "n_probes": 18000,
    "n_endpoints": 120,
    "train_probes": 10800,
    "test_probes": 7200,
}

#: Table 1 as printed: configuration -> (precision, recall, PR-AUC).
PAPER_TABLE1 = {
    "full canary": (0.994, 0.983, 0.861),
    "- delivery rate": (0.976, 0.951, 0.821),
    "- p95 latency": (0.989, 0.972, 0.847),
    "- settlement-to-response gap": (0.943, 0.897, 0.762),
    "- CUSUM (threshold only)": (0.968, 0.929, 0.861),
}

#: Table 3 as printed: stall rate -> price -> DR saved.
PAPER_TABLE3 = {
    "0.10": {"0.001": 8.4e-5, "0.010": 8.4e-4, "0.100": 8.4e-3},
    "0.20": {"0.001": 1.7e-4, "0.010": 1.7e-3, "0.100": 1.7e-2},
    "0.40": {"0.001": 3.4e-4, "0.010": 3.4e-3, "0.100": 3.4e-2},
}

MISSING = "_no generating code_"


def _fmt(v: Any, sig: str = ".4g") -> str:
    if v is None:
        return "—"
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, (int, float)):
        return f"{v:{sig}}"
    return str(v)


def _ci(d: dict[str, Any] | None) -> str:
    if not d:
        return "—"
    return f"[{d['ci_low']:.4g}, {d['ci_high']:.4g}]"


def _row(name: str, paper: Any, pub: Any, spec: Any, note: str = "", sig: str = ".4g") -> str:
    return f"| {name} | {_fmt(paper, sig)} | {_fmt(pub, sig)} | {_fmt(spec, sig)} | {note} |"


def build(
    published: dict[str, Any],
    spec_oracle: dict[str, Any],
    spec_forecast: dict[str, Any],
    ablations: dict[str, Any] | None = None,
) -> str:
    pm = published["metrics"]
    pc = pm["economic-canary"]
    fm = spec_forecast["metrics"]
    fc = fm["economic-canary"]
    om = spec_oracle["metrics"]
    oc = om["economic-canary"]
    fci = fm.get("confidence_intervals", {})

    L: list[str] = []
    A = L.append

    A("# Paper vs. code — computed delta report")
    A("")
    A("Generated by `casper_pay_guard.report`. Nothing here modifies the paper or the")
    A("Zenodo record; this is what the code actually produces.")
    A("")
    A("**Columns.** *paper* = printed in the PDF. *published cfg* = the frozen")
    A("reproduction path (`casper_pay_guard.repro`, 60 endpoints x 120 trials = 7,200")
    A("probes, StandardScaler + LogisticRegression, seeds 7/11/2026). *paper-spec cfg* =")
    A("Section 5 as written (120 endpoints x 150 trials = 18,000 probes, seed 42,")
    A("HistGradientBoosting + isotonic calibration), in forecast mode.")
    A("")

    # -- 1. headline -------------------------------------------------------
    A("## 1. Headline metrics")
    A("")
    A("| metric | paper | published cfg | paper-spec cfg | note |")
    A("|---|---|---|---|---|")
    A(_row("stalled precision", PAPER["stalled_precision"], pc["precision"], fc["precision"]))
    A(_row("stalled recall", PAPER["stalled_recall"], pc["recall"], fc["recall"]))
    A(_row("F2", PAPER["f2"], pc["f2"], fc["f2"]))
    A(_row("PR-AUC", PAPER["pr_auc"], pc["pr_auc"], fc["pr_auc"]))
    A(_row("Brier", PAPER["brier"], pc["brier"], fc["brier"]))
    A(_row("reliability", PAPER["reliability"], pc["reliability"], fc["reliability"]))
    A(_row("resolution", PAPER["resolution"], pc["resolution"], fc["resolution"]))
    A(
        _row(
            "CUSUM median latency",
            PAPER["cusum_median"],
            pm["cusum"]["median_latency_calls"],
            fm["cusum"]["median_latency_calls"],
        )
    )
    A(_row("ARL to false alarm", PAPER["arl"], pm["cusum"]["arl_to_false_alarm"], fm["cusum"]["arl_to_false_alarm"]))
    A(_row("DeLong AUC (canary)", PAPER["delong_auc"], pm["significance"]["delong"]["402-as-healthy-liveness"]["auc_canary"], fm["significance"]["delong"]["402-as-healthy-liveness"]["auc_canary"]))
    A("")
    A("**Every published-cfg value above reproduces the paper exactly** — not to a")
    A("tolerance, bit-for-bit. `tests/test_reproduce.py` asserts it.")
    A("")

    # -- 2. confidence intervals -------------------------------------------
    A("## 2. Confidence intervals — previously unbacked")
    A("")
    A("The paper prints 95% CIs on four metrics from a \"2,000-resample paired")
    A("bootstrap\". No code computed them. Now computed, clustered by endpoint (probes")
    A("from one provider are correlated, so resampling individual probes would")
    A("understate the interval).")
    A("")
    A("| metric | paper CI | paper-spec cfg CI (computed) |")
    A("|---|---|---|")
    for key, label in [
        ("stalled_precision", "stalled precision"),
        ("stalled_recall", "stalled recall"),
        ("pr_auc", "PR-AUC"),
        ("brier", "Brier"),
    ]:
        lo, hi = PAPER[f"{key}_ci"]
        A(f"| {label} | [{lo:.4g}, {hi:.4g}] | {_ci(fci.get(key))} |")
    A("")

    # -- 3. savings --------------------------------------------------------
    A("## 3. Expected USDC saved per routed call")
    A("")
    A("The published run evaluated one routing policy: **pay with probability p-hat**.")
    A("Section 4 motivates a different one — \"a well-calibrated probability translates")
    A("directly into correct expected-value routing\" — which is the threshold rule")
    A("**pay iff p-hat x value > price**. The distinction is not cosmetic: at value")
    A("$0.02 and price $0.001, a provider delivering 65% of the time is worth paying")
    A("every single time, yet the soft policy skips it a third of the time and forgoes")
    A("more value than the stalls it avoids.")
    A("")
    A("| policy | paper | published cfg | paper-spec cfg |")
    A("|---|---|---|---|")
    sp = fm.get("usdc_saved_by_policy", {})
    A(
        f"| soft (pay w.p. p-hat) | {PAPER['saved_dr']:.4g} | "
        f"{pm['usdc_saved_per_call']['dr']:.4g} | {_fmt(sp.get('soft', {}).get('dr'))} |"
    )
    A(f"| ev (pay iff p*v > c) | {MISSING} | — | {_fmt(sp.get('ev', {}).get('dr'))} |")
    A("")
    if sp.get("soft", {}).get("dr", 0) < 0 < sp.get("ev", {}).get("dr", 0):
        A("Under the paper-spec corpus the soft policy is **net negative** and the")
        A("expected-value policy is **net positive with a CI excluding zero**. The")
        A("paper's qualitative claim — routing on canary verdicts beats always-pay —")
        A("holds, but only under the decision rule Section 4 describes, not the one the")
        A("code evaluated. In the published run the two agree, because oracle-mode")
        A("probabilities are already near 0 or 1 and the soft policy rarely abstains.")
        A("")

    # -- 4. framing --------------------------------------------------------
    A("## 4. Oracle mode vs forecast mode")
    A("")
    A("The published predictor is fed the **current probe's own** post-payment")
    A("observables: `artifact_valid`, `schema_valid`, `http_status`, its own gap")
    A("(`repro/canary.py:16-28`). That grades a call which already happened. The")
    A("abstract sells something else — \"an honest probability that your **next** paid")
    A("call will deliver\" — and Section 3 defines the features as history")
    A("(`z_{e,t}` over delivery rate, p95 latency, gap history).")
    A("")
    A("Both are implemented and both are reported:")
    A("")
    A("| framing | features | target | stalled P | stalled R | PR-AUC | Brier |")
    A("|---|---|---|---|---|---|---|")
    A(
        f"| oracle | same-probe observables | this call | {oc['precision']:.3f} | "
        f"{oc['recall']:.3f} | {oc['pr_auc']:.3f} | {oc['brier']:.4f} |"
    )
    A(
        f"| forecast | causal endpoint history | next call | {fc['precision']:.3f} | "
        f"{fc['recall']:.3f} | {fc['pr_auc']:.3f} | {fc['brier']:.4f} |"
    )
    A("")
    A("Oracle mode reaches a perfect 1.000 on the paper-spec corpus. That is not a")
    A("better detector — it is close to a tautology: you cannot consult it before")
    A("paying, because obtaining its features *is* the paid call. Forecast mode is")
    A("strictly harder and is the only one of the two that can inform routing.")
    A("")
    A("Forecast mode misses two of the paper's Table 2 acceptance targets:")
    for k, v in fm["validation_criteria"].items():
        if not v:
            A(f"* `{k}`")
    A("")
    A("These are reported as computed. Nothing was tuned to close them.")
    A("")

    # -- 5. ablations ------------------------------------------------------
    if ablations:
        A("## 5. Table 1 — component ablation (previously unbacked)")
        A("")
        t1_f = ablations.get("table1_forecast", {}).get("rows", {})
        t1_o = ablations.get("table1_oracle", {}).get("rows", {})
        A("| configuration | paper P / R / PR-AUC | oracle cfg | forecast cfg |")
        A("|---|---|---|---|")
        for name, (p, r, a) in PAPER_TABLE1.items():
            o = t1_o.get(name)
            f = t1_f.get(name)
            os_ = f"{o['precision']:.3f} / {o['recall']:.3f} / {o['pr_auc']:.3f}" if o else "—"
            fs = f"{f['precision']:.3f} / {f['recall']:.3f} / {f['pr_auc']:.3f}" if f else "—"
            A(f"| {name} | {p:.3f} / {r:.3f} / {a:.3f} | {os_} | {fs} |")
        A("")
        A("The paper's qualitative claim — that removing the settlement-to-response gap")
        A("hurts most — **reproduces in oracle mode** (it is the only removal that moves")
        A("precision or recall) but the magnitude does not: the paper reports PR-AUC")
        A("falling to 0.762, and the computed drop is far smaller. In forecast mode the")
        A("gap enters only as a rolling mean and removing it barely matters.")
        A("")
        A("The caption's invariant — PR-AUC unchanged when only CUSUM is removed —")
        A("holds in both framings.")
        A("")

        t3 = ablations.get("table3", {})
        if t3:
            A("## 6. Table 3 — savings grid (previously unbacked)")
            A("")
            A("DR USDC saved per routed call, by per-call price (columns) and stall base")
            A("rate (rows).")
            A("")
            for policy in ("soft", "ev"):
                grid = t3.get("grid", {}).get(policy, {})
                if not grid:
                    continue
                tag = "pay w.p. p-hat" if policy == "soft" else "pay iff p*v > c"
                A(f"**policy: {policy}** ({tag})")
                A("")
                A("| stall rate | $0.001 (paper / computed) | $0.01 (paper / computed) | $0.10 (paper / computed) |")
                A("|---|---|---|---|")
                for sr in ("0.10", "0.20", "0.40"):
                    cells = []
                    for pr in ("0.001", "0.010", "0.100"):
                        paper_v = PAPER_TABLE3[sr][pr]
                        got = grid.get(sr, {}).get(pr, {}).get("dr")
                        cells.append(f"{paper_v:.2g} / {got:.2g}" if got is not None else f"{paper_v:.2g} / —")
                    A(f"| {sr} | " + " | ".join(cells) + " |")
                A("")
            A("The paper's structural claim — savings scale approximately linearly in both")
            A("price and stall base rate — **is reproduced**. Under the expected-value")
            A("policy every cell is positive, as the paper asserts. Magnitudes differ,")
            A("and under the soft policy the cheapest column goes negative.")
            A("")

    # -- 7. corpus ---------------------------------------------------------
    A("## 7. Corpus shape")
    A("")
    A("| quantity | paper | published cfg | paper-spec cfg |")
    A("|---|---|---|---|")
    A(_row("probes", PAPER["n_probes"], 7200, spec_forecast["config"]["n_probes"], sig="d"))
    A(_row("endpoints", PAPER["n_endpoints"], 60, spec_forecast["config"]["n_endpoints"], sig="d"))
    A(_row("train probes", PAPER["train_probes"], 3600, spec_forecast["config"]["train_probes"], sig="d"))
    A(_row("test probes", PAPER["test_probes"], 3600, spec_forecast["config"]["test_probes"], sig="d"))
    A("")
    A("The paper describes the paper-spec column. Its numbers come from the")
    A("published column. See REPRODUCIBILITY.md.")
    A("")
    return "\n".join(L) + "\n"


def main(argv: list[str] | None = None) -> int:
    root = Path(__file__).resolve().parents[2]
    ap = argparse.ArgumentParser(description="Write results/paper_delta.md")
    ap.add_argument("--results", default=str(root / "results"))
    args = ap.parse_args(argv)
    res = Path(args.results)

    from casper_pay_guard import ablation, experiment
    from casper_pay_guard.repro.run import run as run_published

    print("running published (frozen) configuration ...")
    published = run_published(out_dir=res / "published")

    print("running paper-spec, oracle mode ...")
    spec_oracle = experiment.run(mode="oracle", out_dir=res / "paper_spec")
    print("running paper-spec, forecast mode ...")
    spec_forecast = experiment.run(mode="forecast", out_dir=res / "paper_spec")

    print("running ablations (Table 1 x2, Table 3) ...")
    ablations = {
        "table1_forecast": ablation.table1(mode="forecast"),
        "table1_oracle": ablation.table1(mode="oracle"),
        "table3": ablation.table3(mode="forecast", n_boot=500),
    }
    (res / "ablations").mkdir(parents=True, exist_ok=True)
    (res / "ablations" / "ablations.json").write_text(json.dumps(ablations, indent=2, default=float))

    md = build(published, spec_oracle, spec_forecast, ablations)
    out = res / "paper_delta.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md)
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
